fix: merge adapter opts
elixir-tesla/tesla pull request #500
Opened 2021-11-07 01:18 UTC by brenomaia

A simple way to resolve issue #367 , hope I understood it correctly.

2021-12-17 12:13 UTC, teamon requested changes

2021-12-17 12:13 UTC, teamon commented on lib/tesla/middleware/core.ex
> +  def call(env, next, adapter: adapter_opts) do
This pattern will only match `[adapter: x]` or `[adapter: x, other: opt]` but not `[other: ops, adapter: x]`.

2022-05-08 08:40 UTC, teamon commented
@brenomaia 👋 Could you push the requested changes so we can merge this PR? :)

2023-09-10 11:27 UTC, yordis commented
I couldn't modify this PR 😭 so I had to create #613

2023-09-10 11:27 UTC, closed without merging