Allow to specify encoding strategy for query params
elixir-tesla/tesla pull request #558
Opened 2023-02-03 07:19 UTC by RudolfMan

I adapting Tesla in a project when we encode query params with `:rfc3986` and I noticed that, while Tesla provides conveniences to build url encoding query params for us, it doesn't allow to specify the encoding strategy.

TL;DR

This PR allows specifying option `query_encoding: :rfc3986` so that whitespaces in query params will be encoded as "%20".

```elixir
Tesla.get("http://example.com", query: [username: "John Smith"], opts: [query_encoding: :rfc3986])
```
will build the following url
```
http://example.com?username=John%20Smith
```

Also adds optional argument to `Tesla.build_url` and `Tesla.encode_query`.

----
Tesla uses [URI.encode_query/2](https://hexdocs.pm/elixir/1.14.3/URI.html#encode_query/2) to encode query params. Since Elixir 1.12 that function allows to specify the encoding strategy.

> You can specify one of the following encoding strategies:
>
>  - `:www_form` - (default, since v1.12.0) keys and values are URL encoded as per [encode_www_form/1](https://hexdocs.pm/elixir/1.14.3/URI.html#encode_www_form/1). This is the format typically used by browsers on query strings and form data. It encodes " " as "+".
>
>  - `:rfc3986` - (since v1.12.0) the same as `:www_form` except it encodes " " as "%20" according [RFC 3986](https://tools.ietf.org/html/rfc3986). This is the best option if you are encoding in a non-browser situation, since encoding spaces as "+" can be ambiguous to URI parsers. This can inadvertently lead to spaces being interpreted as literal plus signs.
>
> Encoding defaults to `:www_form` for backward compatibility.

2023-02-03 07:21 UTC, yordis commented
Related to: https://github.com/elixir-tesla/tesla/issues/538

2023-02-03 07:27 UTC, yordis requested changes

2023-02-03 07:27 UTC, yordis commented on lib/tesla.ex
> +  @spec build_url(Tesla.Env.url(), Tesla.Env.query(), :rfc3986 | :www_form) :: binary
```suggestion
  @type encoding_strategy :: :rfc3986 | :www_form

  @spec build_url(Tesla.Env.url(), Tesla.Env.query(), encoding_strategy) :: binary
```

Also related to this, what happen if some weird encoding is needed? 

As an example: https://github.com/elixir-tesla/tesla/issues/538#issuecomment-1242348413 I had to do that for a project, and, I am not too familiar with whatever RFCs exists out there.

So, what I created was part of some RFC?
Should we allow some callback to handle the encoding as a scape goat? Maybe add it when somebody asks for it? What would be the workload then?

2023-02-03 07:28 UTC, yordis commented
Thank you so much for taking the time for this. I appreciate it.

2023-02-16 04:01 UTC, yordis commented
Any final thoughts related to our conversation?

2024-10-25 01:53 UTC, yordis approved these changes

2024-10-25 05:11 UTC, yordis commented
@teamon share some love over here! Is the function changing from arity 2 to arity 3 with the default value any concern here?

2024-10-25 06:45 UTC, teamon approved these changes
This is all backwards compatible, looks good to me!

2024-10-25 15:27 UTC, merged